### ISSUE TITLE
why today when i log in to binusmaya all my schedule dissappear?  yesterday it was filled with activities.

### ISSUE THREAD

**Issue by RenatoBF** [chrsep/Kingfish#22]

**Comment by mstephen77** [comment]
@RenatoBF I had the same issue too since yesterday, probably Binusmaya changes the way it logs in again. I tried logging in normally to binusmaya and it redirects me to the newStaff/ page instead of newStudent/. I'm currently unable to check it because of this issue for Chrome browser: https://bugs.chromium.org/p/chromium/issues/detail?id=766715. I'll try to download other browsers meanwhile.

**Comment by chrsep** [comment]
@RenatoBF To update schedule, Portal will first try to fetch all schedule from Binusmaya, if it succeeded, it will then wipe the local database and re-enter the new schedules, if it fails, it shouldn't be doing anything. I think if all schedules suddenly went missing, it would probably be because Binusmaya actually sends an empty array when Portal asks for schedule, so this might be just a temporary bug in Binusmaya. 

Binusmaya has been broken for me this whole morning, but everything has been working again for me right now. I'll probably be able to look into this more this weekend.

**Comment by chrsep** [comment]
I'll close this issue for now, since this is quite old now. Feel free to re-open if there are still any issue.
