### ISSUE TITLE
Cannot Sign In (invalid username or password)

### ISSUE THREAD

**Issue by OwinBlazer** [chrsep/Kingfish#33]
Udah sama persis sama yang dipake kalo masuk ke bimay web, tapi masih gk bisa ya?

**Comment by Joonath** [comment]
Same here, but it's not like our account is being credentially changed (since I can sign in from the official site). I suspect that they changed the hashing method. But still, it's best to check out the   sys_login.php first (did find out another alphanumeric inside that script, maybe worth checking, maybe not since this is my first time reconn'ing at BM scripts)

**Comment by chrsep** [comment]
Sorry for the late reply, i've been quite busy lately. I've been looking at this the last few days, looks like Binusmaya have changed some of it's login mechanism to increase security, but it seems to be easy to be bypassed though so i've implemented a fix.

**Comment by OwinBlazer** [comment]
Alright, it works now! Thanks!
