### ISSUE TITLE
Server acting weird (Binusmaya changed their login page again)

### ISSUE THREAD

**Issue by senacand** [chrsep/Kingfish#37]
Portal is no longer working due to Binusmaya changing their login page again. It seems like they've removed all those weird _'encryption'_ that they used on the last update and reverted to a normal page.

I haven't tested it, but rolling back to the previous Portal login method should fix the problem. I'll try to fix it and make a PR if I have time. Should be an easy fix.

**Comment by chrsep** [comment]
Thanks @senacand , i've just tried reverting back but it didn't seem to work (wrong username and password), maybe i am missing something or something small in the login changes, i will look more into this.

**Comment by senacand** [comment]
Simply reverting back won't work since Bimay somehow refuse to login when you're trying to log in through mobile (Chrome), which the previous Portal version tries to mimic.

You'll also need to change the header to mimic a desktop Chrome browser. Check my last PR for reference.

**Comment by chrsep** [comment]
I didn't revert the header though, i only reverted the AuthInteractor back to the old login mechanism, but I think i found the problem.
<img width="576" alt="image" src="https://user-images.githubusercontent.com/8491552/39805615-8b10d49c-53a1-11e8-8f43-4d26f7f52fc2.png">
Binusmaya gave 2 set-cookie statement to Portal, but since okhttp will only return one set-cookie when asked, one of the cookie will be left out.

**Comment by senacand** [comment]
Oh, I forgot about that too. On my last PR, the AuthInteractor already handle that too, although it was quite hacky.

**Comment by chrsep** [comment]
Oh thanks, i missed that😝, It's fixed now though with 2c8ae16486075e10109dea8e6bef89db8d65d15d on my machine, the key for the login button were also changed apparently. i'll roll out the update soon.

**Comment by senacand** [comment]
Alright then. I guess this issue is done now 👍
